import argparse
from pathlib import Path
import sys


PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

from src.semantic_ai.config import ANALYSIS_ZONE, EMBEDDING_DASHBOARD_PATH
from src.semantic_ai.embedding_dashboard import build_embedding_dashboard


def main() -> None:
    parser = argparse.ArgumentParser(description="Build the HTML dashboard for KG embedding clusters.")
    parser.add_argument(
        "--csv",
        type=Path,
        default=ANALYSIS_ZONE / "kg_embedding_clusters.csv",
        help="Input CSV generated by scripts/run_embedding_ml.py",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=EMBEDDING_DASHBOARD_PATH,
        help="Output HTML dashboard path",
    )
    args = parser.parse_args()

    dashboard_path = build_embedding_dashboard(args.csv, args.out)
    print(f"Dashboard written to {dashboard_path}")


if __name__ == "__main__":
    main()
